name: Deploy BirthdayQuest to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout code
      uses: actions/checkout@v4

    - name: 🔐 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # You can use your existing ${{ secrets.AWS_REGION }} if defined

    - name: 📂 Upload index.html to S3
      run: |
        BUCKET_NAME=susan-birthday-quest-uniqueid

        echo "Uploading index.html to s3://$BUCKET_NAME/index.html"
        aws s3 cp html/index.html s3://$BUCKET_NAME/index.html --acl public-read --content-type text/html
